require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
  NewCops: enable
inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  IgnoredMethods: ['describe', 'context']
Style/Documentation:
  Enabled: false
RSpec/NestedGroups:
  Max: 7
RSpec/MultipleMemoizedHelpers:
  Max: 7
RSpec/MultipleExpectations:
  Enabled: false
