default: &default
  url: redis://redis:6379/12

development:
  <<: *default

test:
  <<: *default

preprod:
  <<: *default
  url:  <%= ENV['REDIS_URL_SIDEKIQ'] || 'redis://redis:6379/12' %>

production:
  <<: *default
  url:  <%= ENV['REDIS_URL_SIDEKIQ'] || 'redis://redis:6379/12' %>
